// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmK17n6xJAomy5ImF0wJvBiy3TyS5MgLo',
    appId: '1:888134096023:web:7a9ff8148483240cda45d2',
    messagingSenderId: '888134096023',
    projectId: 'csc-app-de8ac',
    authDomain: 'csc-app-de8ac.firebaseapp.com',
    storageBucket: 'csc-app-de8ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAaa-HUuivduH0_qA8DnM7jvc0HuWnWBU',
    appId: '1:888134096023:android:26c24f8747a473afda45d2',
    messagingSenderId: '888134096023',
    projectId: 'csc-app-de8ac',
    storageBucket: 'csc-app-de8ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1XZ3d7RdW3IcnyJJgi2Y09pOI9yOVKeY',
    appId: '1:888134096023:ios:40831bafb69de2adda45d2',
    messagingSenderId: '888134096023',
    projectId: 'csc-app-de8ac',
    storageBucket: 'csc-app-de8ac.firebasestorage.app',
    iosBundleId: 'com.example.cscMobile',
  );

}